### ISSUE TITLE
substituting other fields into 2-click texts?

### ISSUE THREAD

**Issue by aryairani** [emschwartz/turbo-vpb#1]
Hi — would it be practical to include a way to substitute some of the other sidebar fields, in addition to `[Your Name]` and `[Their Name]`?  e.g.:

> Tomorrow through Nov 1, you can vote early at `[Early Voting Location]` or any regional library, but on election day, you'll need to go to `[Polling Location]` at `[Polling Address]`.

[sample sidebar image](https://user-images.githubusercontent.com/538571/96378200-6d17c280-1158-11eb-9880-06f765f852da.png), [sample sidebar html](https://gist.github.com/aryairani/52b157463ecdff9a63b57cb1a270498a)

**Comment by emschwartz** [comment]
Hi @aryairani, thanks for the suggestion (and for including the screenshot and HTML). I like the idea!

What are those fields listed as in EveryAction? Are they "Additional Contact Details" or something else?

Would you enable them for a VPB under this menu? (I'd like to set them up for my testing VPB)
![image](https://user-images.githubusercontent.com/3262610/96386719-ff28c680-116a-11eb-8890-9a5ddb1b1b72.png)

It should be possible to add this kind of substitution.

**Comment by aryairani** [comment]
Sorry, I am kind of new to this, just a new calling volunteer.  What is EveryAction?  Is that the software that's used to construct the phone bank?

**Comment by emschwartz** [comment]
Oh yeah, it is but no worries! I'll see if I can figure it out on the backend

**Comment by emschwartz** [comment]
Can you send an email to the email listed on the website? I'm going to release a new beta version with this feature included that you can try out. I'll give you instructions for how to install it

**Comment by emschwartz** [comment]
Support for this has been added in version 0.9.0.

Thanks again for the suggestion!
